# Generated by Django 5.0.7 on 2025-05-02 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('Id_Unico', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Id_Combinado', models.CharField(max_length=20, null=True, unique=True)),
                ('Nombre_Completo', models.CharField(max_length=100)),
                ('Seudonimo', models.CharField(max_length=100)),
                ('Contraseña', models.CharField(max_length=100)),
                ('Posicion_fija', models.DecimalField(decimal_places=0, max_digits=38)),
                ('Correo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'EMPLEADO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id_nivel', models.AutoField(primary_key=True, serialize=False)),
                ('descrp_nivel', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'NIVEL',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('descrp_rol', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ROL',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=100)),
                ('horario_inicio', models.DateTimeField()),
                ('horario_fin', models.DateTimeField()),
            ],
            options={
                'db_table': 'TURNO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Directivo',
            fields=[
                ('id_directivo', models.AutoField(primary_key=True, serialize=False)),
                ('contraseña_acceso', models.CharField(max_length=50)),
                ('Id_unico', models.ForeignKey(db_column='Id_unico', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='formulario.empleado')),
            ],
            options={
                'db_table': 'DIRECTIVO',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_nivel',
            field=models.ForeignKey(db_column='id_nivel', on_delete=django.db.models.deletion.CASCADE, to='formulario.nivel'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='formulario.rol'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_turno',
            field=models.ForeignKey(db_column='id_turno', on_delete=django.db.models.deletion.CASCADE, to='formulario.turno'),
        ),
    ]
