# Generated by Django 5.0.7 on 2025-05-04 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='registrosistema',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sesiontiempo',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='actividad',
            table='ACTIVIDAD',
        ),
        migrations.AlterModelTable(
            name='registrosistema',
            table='REGISTRO_SISTEMA',
        ),
        migrations.AlterModelTable(
            name='sesiontiempo',
            table='SESION_TIEMPO',
        ),
    ]
