# Generated by Django 5.0.7 on 2025-05-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_alter_actividad_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='inicial',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
