# Generated by Django 5.0.7 on 2025-05-04 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_alter_actividad_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='id_turno',
            field=models.ForeignKey(blank=True, db_column='id_turno', null=True, on_delete=django.db.models.deletion.CASCADE, to='formulario.turno'),
        ),
    ]
