# Generated by Django 5.0.7 on 2025-05-09 23:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_alter_empleado_id_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosistema',
            name='marca_tiempo',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sesiontiempo',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
