# Generated by Django 5.0.7 on 2025-05-09 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0005_alter_registrosistema_marca_tiempo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrosistema',
            name='marca_tiempo',
        ),
    ]
