# Generated by Django 5.0.7 on 2025-05-09 23:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0006_remove_registrosistema_marca_tiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosistema',
            name='marca_tiempo',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
