# Generated by Django 5.0.7 on 2025-05-10 00:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0008_alter_registrosistema_marca_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosistema',
            name='marca_tiempo',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
