# Generated by Django 5.0.7 on 2025-05-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0009_alter_registrosistema_marca_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesiontiempo',
            name='excedido',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
